#!/usr/bin/env python3
"""Generate README.md from the docs in `docs/`.

The docs are the single source of truth. This assembles a polished README —
badges, install + quickstart (pulled from the doc pages), a documentation table,
and a testing section — so the README never drifts from the docs.

Run after editing anything under `docs/`:

    python scripts/gen_readme.py

CI may re-run it and assert no diff to catch drift.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

OWNER = "shipeasy-ai"
REPO = "sdk-python"
PYPI = "shipeasy"
BLOB = f"https://github.com/{OWNER}/{REPO}/blob/main"
PAGES_SITE = f"https://{OWNER}.github.io/{REPO}"

# One-line "what" for the docs table, keyed by manifest page key. Falls back to
# the page's own lead paragraph when not listed here.
PAGE_BLURB = {
    "overview": "The `configure()` + `Client(user)` model.",
    "installation": "Install, frameworks (Django / Flask / FastAPI), `configure()` wiring.",
    "configuration": "Keys, `attributes`, one-shot vs poll, every option.",
    "flags": "`get_flag`, `get_flag_detail`, defaults.",
    "configs": "`get_config`, typed decode, defaults.",
    "killswitches": "`get_killswitch`, named switches.",
    "experiments": "`get_experiment`, `log_exposure`, `track`.",
    "i18n": "SSR loader tag (rendering is client-side).",
    "error-reporting": "`see()` structured error reporting.",
    "testing": "`configure_for_testing` / `configure_for_offline`, overrides.",
    "openfeature": "`ShipeasyProvider` (OpenFeature server provider).",
    "advanced": "Anon-id middleware, private attributes, sticky bucketing, SSR.",
    "admin-api": "Optional `shipeasy.admin` client for administering resources (generated from the OpenAPI spec).",
}
PAGE_TITLE = {
    "overview": "Overview",
    "installation": "Installation",
    "configuration": "Configuration",
    "flags": "Feature flags",
    "configs": "Dynamic configs",
    "killswitches": "Kill switches",
    "experiments": "Experiments",
    "i18n": "Internationalization",
    "error-reporting": "Error reporting",
    "testing": "Testing",
    "openfeature": "OpenFeature",
    "advanced": "Advanced",
    "admin-api": "Admin API client",
}


def read(rel: str) -> str:
    return (DOCS / rel).read_text(encoding="utf-8")


def absolutize(text: str) -> str:
    """Rewrite relative `(page.md)` links (as they appear inside docs/pages/) to
    absolute GitHub blob URLs, so pulled prose links work from the repo root."""
    return re.sub(
        r"\]\((?!https?://|/)([\w./-]+?\.md)(#[\w-]+)?\)",
        lambda m: f"]({BLOB}/docs/pages/{m.group(1)}{m.group(2) or ''})",
        text,
    )


def first_code(md: str, lang: str) -> str:
    m = re.search(r"```" + lang + r"\n(.*?)```", md, re.S)
    return m.group(1).rstrip() if m else ""


def lead_paragraph_md(md: str) -> str:
    """First real paragraph after the H1, with its Markdown kept."""
    out: list[str] = []
    started = False
    for ln in md.splitlines():
        if not started:
            started = ln.startswith("# ")
            continue
        s = ln.strip()
        if s == "":
            if out:
                break
            continue
        if s.startswith(("#", "```", ">", "|", "-", "<")):
            if out:
                break
            continue
        out.append(s)
    return re.sub(r"\s+", " ", " ".join(out)).strip()


def lead_paragraph(md: str) -> str:
    """First real paragraph after the H1, flattened to plain text."""
    text = lead_paragraph_md(md)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\[(.+?)\]\([^)]*\)", r"\1", text)
    return text.strip()


def main() -> None:
    manifest = json.loads(read("manifest.json"))
    pages = manifest["pages"]  # ordered: fixed key vocabulary

    install = first_code(read("pages/installation.md"), "bash") or "pip install shipeasy"
    quickstart = first_code(read("pages/overview.md"), "python")
    testing_md = read("pages/testing.md")
    testing_lead = absolutize(lead_paragraph_md(testing_md))
    testing_code = first_code(testing_md, "python")

    rows = []
    for key in pages:
        title = PAGE_TITLE.get(key, key.replace("-", " ").title())
        blurb = PAGE_BLURB.get(key) or lead_paragraph(read(pages[key]))
        if len(blurb) > 90:
            blurb = blurb[:87].rstrip() + "…"
        rows.append(f"| [{title}]({BLOB}/docs/pages/{key}.md) | {blurb} |")
    docs_table = "\n".join(rows)

    readme = f"""<!--
  This file is GENERATED by scripts/gen_readme.py from docs/.
  Do NOT edit by hand — edit the docs, then run: python scripts/gen_readme.py
-->

# shipeasy (Python)

[![Tests](https://github.com/{OWNER}/{REPO}/actions/workflows/tests.yml/badge.svg)](https://github.com/{OWNER}/{REPO}/actions/workflows/tests.yml)
[![PyPI](https://img.shields.io/pypi/v/{PYPI}.svg)](https://pypi.org/project/{PYPI}/)
[![Python](https://img.shields.io/pypi/pyversions/{PYPI}.svg)](https://pypi.org/project/{PYPI}/)

Server SDK for [Shipeasy](https://shipeasy.dev) — **feature flags, dynamic
configs, kill switches, A/B experiments, and metric tracking**. Server-key only;
never embed in a browser.

> 📚 **Full documentation:** **<{PAGES_SITE}/>** — also browsable under
> [`docs/`]({BLOB}/docs). This README is generated from those docs.

## 🤖 Using an AI agent?

This SDK ships an installable **agent skill** — a copy-paste-ready guide to
`configure()` + `Client(user)`, testing, experiments, error reporting, and more,
with links the agent can pull for deeper docs:

- **Skill:** [`docs/skill/SKILL.md`]({BLOB}/docs/skill/SKILL.md) · raw:
  `{PAGES_SITE}/skill/SKILL.md`
- **Install it** (ships with the package — no network):
  `shipeasy-skill install` → `.claude/skills/shipeasy-{manifest["sdk"]}/SKILL.md`
  (or via the Shipeasy CLI: `shipeasy docs skill --sdk {manifest["sdk"]} --install`)

**Humans:** you can copy that skill straight into your own project's agent skills
directory (e.g. `.claude/skills/shipeasy-{manifest["sdk"]}/SKILL.md`) so your
coding agent always uses the correct Shipeasy patterns. Every doc page and snippet
is also fetchable by URL — start from the manifest at `{PAGES_SITE}/manifest.json`.

## Install

```bash
{install}
```

Requires Python 3.9+. Per-framework setup (Django / Flask / FastAPI) and the
anon-id middleware are on the [Installation]({BLOB}/docs/pages/installation.md) page.

## Quickstart — `configure()` once, then `Client(user)` per request

```python
{quickstart}
```

Constructing `Client(user)` before `configure()` raises `RuntimeError`.

## Documentation

| Page | What |
| --- | --- |
{docs_table}

Copy-paste snippets live under [`docs/snippets/`]({BLOB}/docs/snippets)
(release · metrics · i18n · ops); an installable agent skill is at
[`docs/skill/SKILL.md`]({BLOB}/docs/skill/SKILL.md).

## Testing

{testing_lead}

```python
{testing_code}
```

More — the on-the-spot override helpers and a working example
`shipeasy-snapshot.json` — on the [Testing]({BLOB}/docs/pages/testing.md) page.

## License

MIT. Evaluation is tested against the cross-language MurmurHash3 vectors in
`experiment-platform/04-evaluation.md`.
"""

    (ROOT / "README.md").write_text(readme, encoding="utf-8")
    print(f"Wrote README.md ({len(readme)} bytes) from {len(pages)} doc pages.")


if __name__ == "__main__":
    main()
